---
title: "Genomics Workshop: Task 1"
author: 
  Ruining Dong^[dong.rn@wehi.edu.au], 
  James Fu, Daniel Cameron
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Genomic Workshop Task 1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## BWA

```{bash}
bwa mem -t $(nproc) chr7.fa normal_R1.fastq.gz normal_R2.fastq.gz | samtools sort -@ $(nproc) - > normal.bam
bwa mem -t $(nproc) chr7.fa tumour_R1.fastq.gz tumour_R2.fastq.gz | samtools sort -@ $(nproc) - > tumour.bam
samtools index normal.bam
samtools index tumour.bam
configureStrelkaSomaticWorkflow.py --normalBam normal.bam --tumorBam tumour.bam --referenceFasta chr7.fa --runDir strelka
strelka/runWorkflow.py -j $(nproc) -m local
```

https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/quickStart.md

## samtools

```{bash}
samtools ...
```





